on:
  push:
    branches:
      - master

concurrency: build

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: "linux/amd64,linux/arm64,linux/arm/v8"
          context: "."
          file: "Dockerfile"
          push: true
          tags: "ghcr.io/white-label-ecommerce/mailhog:latest"


